app: ZoningApiSmartCitizen
service: zoningapismartcitizen

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app
  domain:
    dev: dev.zoning.smartcitizen.tec.br
    prod: api.zoning.smartcitizen.tec.br
  customDomain:
    basePath: ''
    domainName:  ${self:custom.domain.${opt:stage, 'dev'}}
    stage: ${opt:stage, 'dev'}
    createRoute53Record: true  
  pythonRequirements:
    dockerizePip: true    
    slim: true
    useStaticCache: true
    useDownloadCache: true
    invalidateCaches: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, 'dev'}  

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          timeout: 300

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
